name: push
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.4'
      - name: Setup Hugo
        uses: https://github.com/peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true
      - name: build
        run: hugo --minify
      - name: Deploy to SFTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.0
        with:
          server: ${{ secrets.NFSN_HOSTNAME }}
          username: ${{ secrets.NFSN_USERNAME }}
          password: ${{ secrets.NFSN_PASSWORD }} # Uncomment if using password
          # ssh_private_key: ${{ secrets.SFTP_PRIVATE_KEY }} # Uncomment if using SSH key
          local_dir: ./public/ # Adjust to your build output directory
          remote_dir: /home/public/ # Adjust to your web server's target directory
          protocol: sftp
