name: Hugo Deploy
run-name: cassie is testing out Actions 🚀
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: docker
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod
      - name: setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.1"
      - name: setup Hugo
        uses: https://github.com/peaceiris/actions-hugo@v3
        with:
          hugo-version: "latest"
          extended: false
      - name: build site
        run: hugo --minify

      - name: 📂 SFTP uploader # Upload to SFTP
        uses: https://github.com/wangyucode/sftp-upload-action@v2.0.4
        with:
          host: ${{ secrets.NFSN_HOSTNAME }} # Recommended to put the credentials in github secrets.
          username: ${{ secrets.NFSN_USERNAME }}
          password: ${{ secrets.NFSN_PASSWORD }}
          compress: false # Compression
          forceUpload: true # Optional, Force uploading all files, Default to false(upload only newer files).
          localDir: "/public/" # Required, Absolute or relative to cwd.
          remoteDir: "/home/public" # Required, Absolute path only.
          exclude: ".git,.DS_Store,**/node_modules" # Optional. exclude patterns (glob) like .gitignore, use ',' to split, Default to ''.


      - run: echo "🍏 This job's status is ${{ job.status }}."